version: '3.8'  
services:

  api:
    build: 
      context: .
      dockerfile: Dockerfile.node
    container_name: api_node
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
    networks:
      - webnet
    depends_on:
      - db

  db:
    image: postgres:13.3-alpine
    container_name: api_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      PGDATA: ${PGDATA}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - webnet

  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    container_name: api_nginx
    ports:
      - "80:80"
    networks:
      - webnet

volumes:
  db_data:

networks:
  webnet: