version: '3.5'

services:

  api:
    build: 
      context: .
      dockerfile: Dockerfile.node
    container_name: api_node
    labels:
      com.docker.compose.project: schedule-queue
    entrypoint: sh -c "npm install && npm run start:dev"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - .:/home/node/app
      - /home/node/app/node-modules
    ports:
      - ${PORT}:${PORT}
    networks:
      - schedule_queue
    depends_on:
      - db
      - redis
      - nginx

  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: api_db
    labels:
      com.docker.compose.project: schedule-queue
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      PGDATA: ${PGDATA}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - schedule_queue

  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    container_name: api_nginx
    labels:
      com.docker.compose.project: schedule-queue
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    networks:
      - schedule_queue
  
  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    labels:
      com.docker.compose.project: schedule-queue
    hostname: ${HOST_REDIS}
    ports:
      - ${PORT_REDIS}:${PORT_REDIS}
    networks:
      - schedule_queue

volumes:
  db_data:

networks:
  schedule_queue:
    name: shedule-queue